name: '[Release] Build service images'
on:
    push:
        branches:
            - master
            - staging/**
    # pull_request:
    merge_group:

concurrency:
    group: pulls/${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    nango-server:
        uses: ./.github/workflows/push-container.yaml
        secrets: inherit
        with:
            package: server
            run-cmd: build:prod
            tags: -t nangohq/nango-server:${{ github.event.pull_request.head.sha || github.sha }}
    nango-server-self-hosted:
        if: github.ref == 'refs/heads/master'
        uses: ./.github/workflows/push-container.yaml
        secrets: inherit
        with:
            package: server
            run-cmd: build:hosted
            tags: -t nangohq/nango-server:hosted -t nangohq/nango-server:hosted-${{ github.event.pull_request.head.sha || github.sha }}
